config/routes.rb
Rails.application.routes.draw do
  resources :plot, only: [:show, :update] do
    get "filter", to: "plot_filter#index", on: :collection
  end

  resources :person, only: [:index, :edit, :update] do
    get "actived", to: "person#actived", on: :collection
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "plot#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hunter_location.rb
class HunterLocation < ApplicationRecord
  SRID = 28406
  
  validates :location, :date, presence: true
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :plot
  belongs_to :person
  has_one :plot_datum, through: :plot

  validates :plot_id, :person_id, presence: true
  validates :plot_id, uniqueness: {scope: :active_to}, unless: :active_to?
end

app/models/person.rb
class Person < ApplicationRecord
  include Discard::Model

  has_many :owners
  has_many :plots, through: :owners

  def full_name
    [surname, first_name, middle_name].join(" ")
  end

  def member
    member_from.strftime("%d.%m.%Y")
  end
end

app/models/plot.rb
class Plot < ApplicationRecord
  self.primary_key = :number

  has_one :plot_datum, dependent: :destroy
  has_many :owners
  has_one :owner, -> { where(active_to: nil) }
  has_many :persons, through: :owners
  has_one :person, through: :owner

  validates :gid, :area, :perimetr, :number, presence: true
  validates :number, numericality: true
end

app/models/plot_datum.rb
class PlotDatum < ApplicationRecord
  belongs_to :plot

  enum :sale_status, {nothing: "не продается", for_sale: "продается"}
  enum :owner_type, {personal: "личная собственность", state: "государственная собственность"}

  validates :plot_id, presence: true
  validates :kadastr_number, uniqueness: true, format: { with: /\A\d{1,2}:\d{1,2}:\d{1,7}:\d{1,9}\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from NoMethodError, with: :not_implemented

  private

  def not_implemented
    render json: {
             message: "the method not implemented"
           },
      status: 501
  end
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def index
    respond_to do |format|
      format.html { @people = Person.all.order(:surname).includes(:owners) }

      format.json do
        @people = Person.send(params[:type]).order(:surname)
        render json: Panko::ArraySerializer.new(@people, each_serializer: PersonSerializer).to_json
      end
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    Person.find(params[:id]).update(person_params)
    redirect_to person_index_path
  end


  private

  def person_params
    params.require(:person).permit(:surname, :first_name, :middle_name, :tel, :address)
  end
end

app/controllers/plot_controller.rb
class PlotController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  # GET /
  def index
    @people = Person.all.order(:surname)
  end

  # GET /plot/1 or /plot/1.json
  def show
    render json: PlotSerializer.new.serialize_to_json(Plot.find(params[:id]))
  end

  # PATCH/PUT /plot/1 or /plot/1.json
  def update
    plot = PlotUpdater.new.call(params.require(:id), owner_params[:person_id].to_i, plot_data_params)

    if plot.success?
      render json: PlotSerializer.new.serialize_to_json(plot.success), status: 200
    else
      render json: {message: plot.failure}, status: 400
    end
  end

  private

  def owner_params
    params.require(:owner).permit(:person_id)
  end

  def plot_data_params
    params.require(:plot_data).permit(:sale_status, :owner_type, :description)
  end
end

app/controllers/plot_filter_controller.rb
class PlotFilterController < ApplicationController
  NO_MATTER = "не важно"

  def index
    query = {}
    query.merge!({owner_type: which_owner}) if which_owner
    query.merge!({sale_status: which_sale_status}) if which_sale_status

    if which_owner || which_sale_status
      plots_numbers = PlotDatum.where(query).map { _1.plot.number }
      render json: {plots: plots_numbers}
    else
      render json: {}
    end
  end

  private

  def which_owner
    (params.require(:owner_type) == NO_MATTER) ? false : params.require(:owner_type)
  end

  def which_sale_status
    (params.require(:sale_status) == NO_MATTER) ? false : params.require(:sale_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chairmansmap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <!-- Leaflet CSS and JS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

    <%= favicon_link_tag 'favicon.png', skip_pipeline: true %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen max-h-screen flex flex-col">
    <header class='w-full text-gray-700 bg-white border-t border-gray-100 shadow-sm body-font'>
      <div class='container flex flex-col items-start justify-between p-6 mx-auto md:flex-row'>
        <a class='flex items-center mb-4 font-medium text-gray-900 title-font md:mb-0'>
        </a>
        <nav class='flex flex-wrap items-center justify-center pl-24 text-base md:ml-auto md:mr-auto'>
            <%= link_to "Карта", root_path, class: 'mr-5 font-medium hover:text-gray-900' %>
            <%= link_to "Участники", person_index_path, class: 'mr-5 font-medium hover:text-gray-900' %>
        </nav>
      </div>
    </header>

    <main class="m-6 w-full-8 flex-auto">
      <%= yield %>
    </main>

    <footer class="p-2 bg-gray-300 text-gray-800">
      <div class="text-sm text-center">
        <p>
          Copyright © 2023 - Andrew
        </p>
      </div>
    </footer>

    <!-- Leaflet Geoserver wfs -->
    <%= javascript_include_tag "L.Geoserver" %>
  </body>
</html>

app/views/person/edit.html.erb
<div class="content-center items-center">

  <%= link_to "Back", person_index_path %>
  
  <h1 class="font-thinner flex text-4xl pt-10 px-5 mb-8">Редактирование <%=@person.full_name%></h1>

  <%= form_for :person, method: :patch, url: person_path(@person), html: {class: "w-1/3 ml-32"} do |f|%>
    <%= f.label :surname, "Фамилия", {:class => "mb-8"} %>
    <%= f.text_field(:surname, {:class =>"mb-8 w-full block text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none"})%>

    <%= f.label :first_name, "Имя"%>
    <%= f.text_field(:first_name, {:class => "mb-8 w-full block text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none"})%>
    
    <%= f.label :middle_name, "Отчество"%>
    <%= f.text_field(:middle_name, {:class => "mb-8 w-full block text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none"})%>
    
    <%= f.label :tel, "Телефон"%>
    <%= f.telephone_field(:tel, {:class => "mb-8 w-full block text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none"})%>

    <%= f.label :address, "Адрес"%>
    <%= f.text_field(:address, {:class => "mb-8 w-full block text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none"})%>
      
    <%= f.submit({:class => "mt-8 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg sm:w-auto px-5 py-2.5 text-center"})%>
    
  <%end%>
</div>

app/views/person/index.html.erb
<%= javascript_include_tag "people" %>

<!--menu bar-->
<div class="mb-5 pb-5 px-5 bg-white rounded shadow-xl">
    <div class="-mx-1">
        <ul class="flex w-full flex-wrap items-center h-10">
            <li class="block relative">
                <input class="peer sr-only" type="radio" value="kept" name="members" id="i1" checked/>
                <label class="people_filter flex justify-center cursor-pointer border border-gray-300 bg-white py-2 px-4 hover:bg-gray-50 focus:outline-none peer-checked:border-transparent peer-checked:ring-2 peer-checked:ring-indigo-500 transition-all duration-500 ease-in-out" for="i1">
                    Активные участники (<%=@people.kept.count%>)
                </label>
            </li>

            <li class="block relative mx-2">
                <input class="peer sr-only" type="radio" value="discarded" name="members" id="i2"/>
                <label class="people_filter flex justify-center cursor-pointer border border-gray-300 bg-white py-2 px-4 hover:bg-gray-50 focus:outline-none peer-checked:border-transparent peer-checked:ring-2 peer-checked:ring-indigo-500 transition-all duration-500 ease-in-out" for="i2">
                    Бывшие участники (<%=@people.discarded.count%>)
                </label>
            </li>

            <li class="block relative">
                <input class="peer sr-only" type="radio" value="all" name="members" id="i3"/>
                <label class="people_filter flex justify-center cursor-pointer border border-gray-300 bg-white py-2 px-4 hover:bg-gray-50 focus:outline-none peer-checked:border-transparent peer-checked:ring-2 peer-checked:ring-indigo-500 transition-all duration-500 ease-in-out" for="i3">
                    Все участники (<%=@people.count%>)
                </label>
            </li>
        </ul>
    </div>
</div>

<!--table with people-->
<div class="px-4 sm:px-8 py-4 overflow-x-auto mx-16" id="for-table">
    <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
        <table class="min-w-full leading-normal">
            <thead>
                <tr>
                    <th
                        class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        ФИО
                    </th>
                    <th
                        class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        Телефон
                    </th>
                    <th
                        class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        Адрес
                    </th>
                    <th
                        class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        Участник с
                    </th>
                    <th
                        class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        Количество участков
                    </th>
                    <th
                        class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                    </th>
                </tr>
            </thead>
            <tbody>

            <%@people.each do |person| %>
                <tr>
                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm flex items-center ml-3">
                        <p class="text-gray-900 whitespace-no-wrap"><%=person.full_name%></p>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                        <p class="text-gray-900 whitespace-no-wrap"><%=person.tel%></p>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                        <p class="text-gray-900 whitespace-no-wrap"><%=person.address%></p>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                        <p class="text-gray-900 whitespace-no-wrap"><%=person.member%></p>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                        <p class="text-gray-900 whitespace-no-wrap"><%=person.owners.map(&:plot).count%></p>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                        <%= link_to "Редактировать", edit_person_path(person) %>
                    </td>
                </tr>
                <%end%>
            </tbody>
        </table>
    </div>
</div>

app/views/plot/index.html.erb
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>
<%= javascript_include_tag "main_map" %>

<div class="flex h-full">
    <!-- map -->
        <div class="mx-4 my-4 w-3/5 max-h-700px">
            <div id="map" class="map w-full h-full"></div>
        </div>

    <!-- form -->
    <div id="data_form" class="p-5 w-2/5 h-full max-h-700px">
        <div class="px-4 pd-4 w-full h-1/5 grid grid-cols-2">

            <div class="grid grid-row-2 mx-1 mb-1">
                <span>Статус продажи</span>
                <select id="filter_sale_status">
                    <%=options_for_select(["не важно", "продается", "не продается"]) %>
                </select>
            </div>
            
            <div id="filters" class="mt-5 mx-1 cursor-pointer text-center text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Фильтровать</div>


            <div class="grid grid-row-2 mx-1 mb-1">
                <span>Тип владения</span>
                <select id="filter_owner_type">
                    <%=options_for_select(["не важно", "личная собственность", "государственная собственность"]) %>
                </select>
            </div>

            <div id="reset_filters" class="mt-5 mx-1 cursor-pointer text-center text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Сбросить</div>

        </div>

        <div class="rounded-lg p-8 flex flex-col w-full shadow-2xl h-4/5">

            <div class="divide-solid devide-y">
                <div class="inline-block text-xl">Данные участка № <b id="plot_number"></b></div>
            </div>

            <!-- data -->
            <div id="show_data_form" class="flex flex-col h-full">
                <div class="flex-auto">

                    <div class="my-10">
                        <div class="mb-3 text-xl">Владелец участка</div>
                        <div>Тип владения: <span id="owner_type"></span></div>
                        <div>ФИО: <span id="owner_fio"></span></div>
                        <div>Тел: <span id="owner_tel"></span></div>
                        <div>Адрес: <span id="owner_adr"></span></div>
                    </div>

                    <div>
                        <div class="mt-5 mb-3 text-xl">Данные участка</div>
                        <div>Кадастровый № <span id="plot_number_kadastr"></span></div>
                        <div>Площадь: <span id="plot_area"></span></div>
                        <div>Периметр: <span id="plot_perimetr"></span></div>
                        <div>Статус продажи: <span id="plot_sale_status"></span></div>
                        <div>
                            <div>Дополнительная информация:</div>
                            <span id="plot_description" class="ml-3"></span>
                        </div>
                    </div>
                    
                </div>

                <button id="open_form_button" href="" disabled class="inset-x-0 bottom-0 text-white bg-indigo-500 border-0 py-2 px-6 enabled:focus:outline-none enabled:hover:bg-indigo-900 rounded text-lg">Обновить данные участка</button>
            </div>

            <!-- update form -->
            <div id="update_data_form" class="hidden h-full">
                <%= form_for(:plot , method: :patch, remote: true, html: {class: "h-full flex flex-col", id: "update_form"}) do |f| %>
                    <div class="flex-auto">
                        <div class="mb-4">
                            <label for="owner" class="block leading-7 text-sm">Владелец участка</label>
                            <select name="owner[person_id]" id="form_person_id">
                                <%=options_for_select(@people.map { ["#{_1.surname} #{_1.first_name} #{_1.middle_name}", _1.id] }) %>
                            </select>
                        </div>

                        <div class="relative mb-4">
                            <label for="form_sale_status" class="block leading-7 text-sm">Статус продажи</label>
                            <select name="plot_data[sale_status]" id="form_sale_status">
                                <%=options_for_select(["не продается", "продается"]) %>
                            </select>
                        </div>

                        <div class="relative mb-4">
                            <label for="form_owner_type" class="block leading-7 text-sm">Тип владения</label>
                            <select name="plot_data[owner_type]" id="form_owner_type">
                                <%=options_for_select(["личная собственность", "государственная собственность"]) %>
                            </select>
                        </div>

                        <div class="relative mb-4">
                            <label for="form_description" class="block leading-7 text-sm">Дополнительная информация</label>
                            <textarea name="plot_data[description]" id="form_description"></textarea>
                        </div>
                    </div>
                
                    <div class="flex w-full inset-x-0 bottom-0">
                        <button type="submit" id="update_data_button" class="w-1/3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Обновить</button>
                        <button type="reset" id="reset_data_button" class="mx-3 w-1/3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Сброс</button>
                        <div id="cancel_data_button" class="w-1/3 cursor-pointer text-center text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Отмена</div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>